# Backend Dockerfile (Strapi v5 dev mode)
FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Expose Strapi port
EXPOSE 1337

# Hot reload env
ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true

CMD ["npm", "run", "develop"]
